/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package littlebagshop;

/**
 *
 * @author my
 */
public class mmenu extends javax.swing.JFrame {

    /**
     * Creates new form mmenu
     */
    public mmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ad4 = new javax.swing.JButton();
        ad3 = new javax.swing.JButton();
        ad2 = new javax.swing.JButton();
        ad1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Previous");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        ad4.setBackground(new java.awt.Color(102, 255, 102));
        ad4.setText("Creat Account");
        ad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad4ActionPerformed(evt);
            }
        });
        getContentPane().add(ad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 170, 40));

        ad3.setBackground(new java.awt.Color(102, 255, 102));
        ad3.setText("Search");
        ad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad3ActionPerformed(evt);
            }
        });
        getContentPane().add(ad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 170, 40));

        ad2.setBackground(new java.awt.Color(102, 255, 102));
        ad2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ad2.setText("View Details");
        ad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad2ActionPerformed(evt);
            }
        });
        getContentPane().add(ad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 260, 170, 40));

        ad1.setBackground(new java.awt.Color(102, 255, 102));
        ad1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ad1.setText("Add New Details");
        ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad1ActionPerformed(evt);
            }
        });
        getContentPane().add(ad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 160, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\my\\Downloads\\image.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad2ActionPerformed
        Mviewdetails app2 = new Mviewdetails();
        this.hide();
        app2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ad2ActionPerformed

    private void ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad1ActionPerformed
        Maddnewdetails app2 = new Maddnewdetails();
        this.hide();
        app2.setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_ad1ActionPerformed

    private void ad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad3ActionPerformed
        Csearch app2 = new Csearch();
        this. hide();
        app2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ad3ActionPerformed

    private void ad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad4ActionPerformed
        creatcashiernewaccount app2 = new creatcashiernewaccount();
        this.hide();
        app2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ad4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad1;
    private javax.swing.JButton ad2;
    private javax.swing.JButton ad3;
    private javax.swing.JButton ad4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
